HallsBooking/HallsBooking/Areas/Agent/Models/BookHall.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using HallsBooking;

namespace HallsBooking.Areas.Agent.Models
{
    public enum FunctionType
    {
        Birthday,
        Marriage,
        Reception,
        GetToGather,
        NamingCeremony
    }
    public class BookHall
    {
        
        public Hall Hall {get;set;}

        public BookingDetail BookingDetail { get; set; }
    }
}

HallsBooking/HallsBooking/Areas/Halls/Models/HallModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallsBooking.Areas.Halls.Models
{
    public class HallModel
    {
        public int HallId { get; set; }
        //public 
    }
}

HallsBooking/HallsBooking/Areas/Agent/Controllers/BookHallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HallsBooking.Areas.Agent.Models;

namespace HallsBooking.Areas.Agent.Controllers
{
    public class BookHallController : Controller
    {
        //
        // GET: /Agent/BookHall/

        public ActionResult BookHall()
        {
            List<FunctionType> EnumValues = new List<FunctionType>();
            EnumValues.Add(FunctionType.Birthday);
            EnumValues.Add(FunctionType.GetToGather);
            EnumValues.Add(FunctionType.Marriage);
            EnumValues.Add(FunctionType.NamingCeremony);
            EnumValues.Add(FunctionType.Reception);

            ViewBag.FunctionType = EnumValues;
            return View();
        }
    }
}

HallsBooking/HallsBooking/Areas/Halls/Controllers/AllHallsController.cs
using HallsBooking.Filters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HallsBooking.Areas.Halls.Controllers
{
    public class AllHallsController : Controller
    {
        SampleEntities db = new SampleEntities();
        // GET: Halls/AllHalls
        public ActionResult Halls()
        {
           // int x = 0;int y = 1;int result = y / x;
            List<Country> countries = db.Countries.ToList();
            ViewBag.Countries = countries;
            return View();
        }

        public ActionResult GetAllHalls(int CityId)
        {
            string id = CityId.ToString();
            var halls = db.Halls.Where(x => x.City == id).ToList();
            //.Select(x => new { x.HallId, x.HallName, x.Address })
            //var hall = db.Halls.Select(x => new { x.HallId, x.HallName, x.Address,x.City }).Where(x=>x.City==id).ToList();
            //  return Json(halls, JsonRequestBehavior.AllowGet);
            return PartialView("HallsDetails", halls);
        }
        /// <summary>
        ///showing the halls
        /// </summary>
        public ActionResult ShowAllHalls()
        {
            List<Hall> halls = db.Halls.OrderBy(h => h.HallId).Take(2).ToList();
            return View(halls);
        }
        /// <summary>
        /// Show more functionality...
        /// </summary>
        [HttpPost]
        [AllowAnonymous]
        public JsonResult ShowMoreHalls(int size)
        {
            //var model = from h in db.Halls
            //             join hi in db.HallImages on h.HallId equals hi.HallId
            //             select new Hall {HallId=h.HallId,HallName=h.HallName };
            var model = db.Halls.OrderBy(h => h.HallId).Skip(size).Take(2);
            int modelCount = db.Halls.Count();
            if(model.Any())
            {
                string modelString = RenderRazorViewToString("_LoadMoreHalls", model);
                return Json(new { ModelString = modelString, ModelCount = modelCount });
            }
            return Json(model);
        }
        /// <summary>
        /// Partial view for Show more halls.
        /// </summary>
        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext =
                     new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
        /// <summary>
        /// Getting the Single Hall Details.
        /// </summary>
        [CustomAuthorize("user")]
        public ActionResult ViewHallDetails(int? id)
        {
            Hall hallDetails = db.Halls.FirstOrDefault(x=>x.HallId==id);
            int countryId = int.Parse(hallDetails.Country);
            int stateId = int.Parse(hallDetails.State);
            int cityId = int.Parse(hallDetails.City);
            ViewBag.CountryName = db.Countries.SingleOrDefault(x => x.CountryId == countryId).CountryName;
            ViewBag.StateName = db.States.SingleOrDefault(x => x.StateId == stateId).StateName;
            ViewBag.CityName = db.Cities.SingleOrDefault(x => x.CityId == cityId).CityName;
            return View(hallDetails);
        }
        /// <summary>
        /// Booking the Hall
        /// </summary>
        /// <param name="id">Hall Id</param>
        [CustomAuthorize("user")]
        public ActionResult BookHall(int id)
        {
            return View();
        }
    }
}

HallsBooking/HallsBooking/Areas/Halls/Views/AllHalls/BookHall.cshtml
@{
    ViewBag.Title = "BookHall";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Booking Hall is under Process...Please wait Some more days</h3>

HallsBooking/HallsBooking/Areas/Halls/Views/AllHalls/Halls.cshtml
@{
    ViewBag.Title = "Halls";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Halls</h2>
<table id="ddls">
    <tr>
        <td>
            @Html.Label("Country", "Select Country")
            @Html.DropDownList("Country", new SelectList(ViewBag.Countries, "CountryId", "CountryName"), "Please Select a Country")
        </td>
        <td>
            @Html.Label("State", "Select State")
            @Html.DropDownList("State", new SelectList(Enumerable.Empty<SelectListItem>(), "StateId", "StateName"), "Please Select a State")
        </td>
        <td>
            @Html.Label("City", "Select City")
            @Html.DropDownList("City", new SelectList(Enumerable.Empty<SelectListItem>(), "CityId", "CityName"), "Please Select a City")
        </td>
    </tr>
</table>

<div id="viewPlaceHolder"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script type="text/javascript">
        $('#Country').change(function () {
            var countryId = $('#Country').val();
            $.ajax({
                url: '/Agent/Users/BindStates',
                type: "Get",
                dataType: "JSON",
                data: { CountryId: countryId },
                success: function (states) {
                    var items = '<option>Please Select a State</option>';
                    $.each(states, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#State').html(items);
                    $('#City').html('<option>Please Select a City</option>');
                },
                Error: function (error) {
                    alert("There is some Error")
                }
            });
        });
        $('#State').change(function () {
            var stateId = $('#State').val();
            $.ajax({
                url: '/Agent/Users/BindCites',
                type: "Get",
                dataType: "JSON",
                data: { StateId: stateId },
                success: function (cites) {
                    var items = '<option>Please Select a City</option>';
                    $.each(cites, function (i, cite) {
                        items += "<option value='" + cite.Value + "'>" + cite.Text + "</option>";
                    });
                    $('#City').html(items);
                },
                Error: function (error) {
                    alert("There is some Error")
                }
            });
        });
        $('#City').change(function () {
            var cityId = $('#City').val();
            $("#viewPlaceHolder").load("/Halls/AllHalls/GetAllHalls",
            { CityID: cityId});
        });

</script>

HallsBooking/HallsBooking/Areas/Halls/Views/AllHalls/HallsDetails.cshtml
@model IEnumerable<HallsBooking.Hall>
<link href="~/Areas/Halls/Content/DataTable.css" rel="stylesheet" />
<script src="~/Areas/Halls/Scripts/DataTable.js"></script>
<script>
    $(document).ready(function () {
        $('#halls').DataTable({
            "scrollY": "200px",
            "scrollCollapse": true,
            "paging": true
        });
    })
</script>
<table id="halls" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>
                Hall Name
            </th>

            <th>
                Address
            </th>

            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.HallName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>

                <td>@Html.ActionLink("View Details", "ViewHallDetails", "AllHalls", new { @id = item.HallId }, null)</td>
                <td>@Html.ActionLink("BookNow", "BookHall", "AllHalls", new { @id = item.HallId }, null)</td>
            </tr>
        }
    </tbody>
</table>

HallsBooking/HallsBooking/Areas/Halls/Views/AllHalls/ShowAllHalls.cshtml
@using HallsBooking.Areas.Halls
@model IEnumerable<Hall>
@{
    ViewBag.Title = "ShowAllHalls";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>ShowAllHalls</h2>
    @foreach (var halls in Model)
    {
        <h3>@Html.ActionLink(halls.HallName, "ViewHalldetails", new { id = halls.HallId })</h3>
        <a href='@Url.Action("ViewHallDetails",new { id=halls.HallId})'> <img src="/Home/RetrieveImage/@halls.HallId" height="400px" width="400px" style="float:left;"></a>

    }*@



<section id="banner" data-video="images/banner">
    <div class="inner">
        <header>
            <h1>Full Motion</h1>
            <p>
                A responsive video gallery template with a functional lightbox<br />
                designed by <a href="https://templated.co/">Templated</a> and released under the Creative Commons License.
            </p>
        </header>
        <a href="#main" class="more" style="align-self:center;">Learn More</a>
    </div>
</section>
<!-- Main -->
<div id="main">
    <div class="inner">
        <!-- Boxes -->
        <div class="thumbnails">
            @foreach (var halls in Model)
            {
                <div class="box">
                    <a href='@Url.Action("ViewHallDetails",new { id=halls.HallId})' class="image fit"> <img src="/Home/RetrieveImage/@halls.HallId"></a>
                    <div class="inner">
                        <h3>@halls.HallName</h3>
                        <p>Interdum amet accumsan placerat commodo ut amet aliquam blandit nunc tempor lobortis nunc non. Mi accumsan.</p>
                        <h3>@Html.ActionLink("View Details", "ViewHalldetails", new { id = halls.HallId },new { @class="button fit" })</h3>
                        @*<a href="https://youtu.be/s6zR2T9vn2c" class="button fit" data-poptrox="youtube,800x400">Watch</a>*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*<link href="~/Areas/Halls/Styles/font-awesome.min.css" rel="stylesheet" />*@
<link href="~/Areas/Halls/Styles/main.css" rel="stylesheet" />
<script src="~/Areas/Halls/Scripts/jquery.min.js"></script>
<script src="~/Areas/Halls/Scripts/jquery.poptrox.min.js"></script>
<script src="~/Areas/Halls/Scripts/jquery.scrolly.min.js"></script>
<script src="~/Areas/Halls/Scripts/main.js"></script>
<script src="~/Areas/Halls/Scripts/skel.min.js"></script>
<script src="~/Areas/Halls/Scripts/util.js"></script>
<img src="~/Images/spinners.gif" id="loading" /><br />
<input type="button" id="loadMore" value="ShowMore" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        var loading = $("#loading");
        loading.hide();
    })
    $(function () {
        var loadCount = 1;
        var loading = $("#loading");
        $("#loadMore").on("click", function (e) {

            e.preventDefault();

            $(document).on({

                ajaxStart: function () {
                    loading.show();
                },
                ajaxStop: function () {
                    loading.hide();
                }
            });

            var url = "/Halls/AllHalls/ShowMoreHalls/";
            $.ajax({
                url: url,
                data: { size: loadCount * 2 },
                cache: false,
                type: "POST",
                success: function (data) {

                    if (data.length !== 0) {
                        $(data.ModelString).insertBefore("#loadMore").hide().fadeIn(2000);
                    }

                    var ajaxModelCount = data.ModelCount - (loadCount * 2);
                    if (ajaxModelCount <= 0) {
                        $("#loadMore").hide().fadeOut(2000);
                    }

                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText);
                    alert("message : \n" +
                        "An error occurred, for more info check the js console" +
                        "\n status : \n" + status + " \n error : \n" + error);
                }
            });

            loadCount = loadCount + 1;
        });
    });
</script>

HallsBooking/HallsBooking/Areas/Halls/Views/AllHalls/ViewHallDetails.cshtml
@using HallsBooking.Areas.Halls
@model Hall
@{
    ViewBag.Title = "ViewHallDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>@Model.HallName</h3>
<img src="/Home/RetrieveImage/@Model.HallId" style="height:400px;width:960px;">
<table border="1" style="text-align:center;">
    <caption style="text-align:center;color:red;font-size:30px;background-color:darkgrey;">Hall Details</caption>
    <tr>
        <td>Hall Name</td>
        <td>@Model.HallName</td>
    </tr>
    <tr>
        <td>Cost With Decoration</td>
        <td>@Model.CostWithDecaration</td>
    </tr>
    <tr>
        <td>Cost With out Decoration</td>
        <td>@Model.CostWithOutDecaration</td>
    </tr>
    <tr>
        <td>Address</td>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <td>LandMark</td>
        <td>@Model.LandMark</td>
    </tr>
    <tr>
        <td>Phone</td>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <td>Mobile</td>
        <td>@Model.Mobile</td>
    </tr>
    <tr>
        <td>Country</td>
        <td>@ViewBag.CountryName</td>
    </tr>
    <tr>
        <td>State</td>
        <td>@ViewBag.StateName</td>
    </tr>
    <tr>
        <td>City</td>
        <td>@ViewBag.CityName</td>
    </tr>
</table>
<div style="height:100px;width:300px;text-align:center;font-size:30px;align-content:center;margin-left:340px;">
    @Html.ActionLink("Book Now", "BookHall", "AllHalls", new { @id = Model.HallId }, null)
</div>